# Generated by Django 2.2.3 on 2021-11-17 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hedgehog', '0002_hedgehog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, verbose_name='期日')),
            ],
            options={
                'verbose_name': 'Todoリスト',
                'verbose_name_plural': 'Todoリスト',
            },
        ),
    ]
